Bugfix/sentry
smileidentity/ios pull request #221
Opened 2024-08-21 12:25 UTC by JNdhlovu

Sentry ios fix

2024-08-21 12:55 UTC, jumaallan commented on Example/SmileID/App/AppDelegate.swift
> +                options.dsn = ArkanaKeys.Global().sENTRY_DSN
is the small s intentional?

2024-08-23 13:37 UTC, jumaallan approved these changes

2024-08-26 11:32 UTC, tobitech requested changes

2024-08-26 11:32 UTC, tobitech commented on Example/SmileID.xcodeproj/project.pbxproj
> +				ENABLE_SENTRY = NO;
@JNdhlovu I noticed that `ENABLE_SENTRY` is enabled for Debug but disabled for Release. Is there a reason why `ENABLE_SENTRY` is set to `NO` for Release?

2024-08-28 10:12 UTC, merged