Feature/better error handling
smileidentity/ios pull request #261
Opened 2024-12-10 13:47 UTC by JNdhlovu

Story: https://app.shortcut.com/smileid/story/13730/improve-error-handling-on-android-and-ios-sdk
Improve Error Handling on android and ios sdk.
## Summary

Better abstraction for 
1. Smartselfie enrollment
2. Smartselfie authentication
3. Document verification
4. Enhanced document verification
5. Biometric KYC

## Known Issues

n/a

## Test Instructions

1. Test the jobs from the orchestrated screens paths
2. Test offline mode 
3. Capture jobs and then use the submitJob method to make sure everything is working fine 

## Screenshot

n/a

2025-01-15 12:52 UTC, tobitech requested changes

2025-01-15 12:52 UTC, tobitech commented on Sources/SmileID/Classes/JobSubmission/Base/BaseSubmissionViewModel.swift
> +                let submissionResult = try await submission.executeSubmission(
`executeSubmission(_:)` isn't a throwing function so the `try` is redundant; Xcode shows a warning for this line.

2025-01-28 09:34 UTC, jumaallan commented on Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift
> +class OrchestratedBiometricKycViewModel: BaseSubmissionViewModel<BiometricKycResult> {
Why are we marking these as non internal?

2025-01-28 09:49 UTC, jumaallan commented on Sources/SmileID/Classes/JobSubmission/Base/BaseDocumentVerificationSubmission.swift
> +//
remove author comments

2025-01-28 09:57 UTC, jumaallan commented on Sources/SmileID/Classes/JobSubmission/Results/SmileIDResults.swift
> +//  SmileIDResults.swift
delete :)

2025-01-28 09:57 UTC, jumaallan commented on Sources/SmileID/Classes/JobSubmission/SelfieSubmission.swift
> +//  SelfieSubmission.swift
delete :)

2025-02-19 00:18 UTC, closed without merging